const STUDY_PLAN_START='2026-09-01';
const PLAN_LIMITS={bangla:120,english:95,math:85,gk:128};
const PLAN_SUBJECTS=[{id:'bangla',name:'📖 বাংলা',source:'banglaTopics'},{id:'english',name:'🇬🇧 English',source:'englishTopics'},{id:'math',name:'➗ Mathematics',source:'mathTopics'},{id:'gk',name:'🌍 General Knowledge',source:'gkTopics'}];
function planDay(){const n=Number(localStorage.getItem('planDay'));return n>=1&&n<=180?n:1}
function planPhase(d){if(d<=30)return'Foundation';if(d<=60)return'Core Build';if(d<=90)return'Core Build + MCQ';if(d<=120)return'Syllabus Finish';if(d<=150)return'1st Full Revision';if(d<=170)return'2nd Revision + Model Tests';return'Final Revision + Full Mock'}
function getTopicArray(source){try{const a=window[source];return Array.isArray(a)?a:[]}catch(e){return[]}}
function buildDailyTopicPlan(){const q={};PLAN_SUBJECTS.forEach(s=>q[s.id]=getTopicArray(s.source).slice(0,PLAN_LIMITS[s.id]));const plan=Array.from({length:120},()=>[]),used={bangla:0,english:0,math:0,gk:0};for(let d=0;d<120;d++){for(let k=0;k<4;k++){let best=null,bestScore=-1;PLAN_SUBJECTS.forEach(s=>{const left=q[s.id].length-used[s.id];if(!left)return;const score=(PLAN_LIMITS[s.id]-used[s.id])/PLAN_LIMITS[s.id];if(score>bestScore){best=s;bestScore=score}});if(!best)break;const i=used[best.id]++;plan[d].push({name:best.name,topic:q[best.id][i],index:i,subject:best.id})}}return plan}
let DAILY_TOPIC_PLAN=[];function getDailyTopicPlan(){if(!DAILY_TOPIC_PLAN.length)DAILY_TOPIC_PLAN=buildDailyTopicPlan();return DAILY_TOPIC_PLAN}
function planTasks(d){const p=getDailyTopicPlan();if(d<=120&&p[d-1]){const a=p[d-1].map(x=>`${x.name}: ${x.topic}`);a.push('📝 40–50 MCQ');a.push('🔄 আগের দিনের পড়া 30 মিনিট Revision');return a}if(d<=150)return['📖 বাংলা: 1st Full Revision','🇬🇧 English: 1st Full Revision','➗ Math: Formula + ভুল অঙ্ক','🌍 GK: 1st Full Revision','📝 60–80 MCQ','⭐ দুর্বল Topic Mark'];if(d<=170)return['📖 বাংলা: 2nd Revision + Previous Questions','🇬🇧 English: 2nd Revision + Vocabulary/Grammar','➗ Math: Previous Questions + Formula','🌍 GK: 2nd Revision + Current/Static GK','📝 100 MCQ','🧪 Model Test + ভুল প্রশ্ন'];return['📖 বাংলা: Final Rapid Revision','🇬🇧 English: Final Rapid Revision','➗ Math: Formula + Previous Questions','🌍 GK: Final Rapid Revision','📝 100–150 MCQ','🔥 Full Mock Test','❌ ভুল প্রশ্ন Final Revision']}
function render180DayPlan(){const d=planDay(),t=document.getElementById('planDay'),box=document.getElementById('planTasks'),p=document.getElementById('planProgress'),dt=document.getElementById('planDate');if(!t||!box)return;t.textContent=`Day ${d} / 180 • ${planPhase(d)}`;const x=new Date(STUDY_PLAN_START+'T00:00:00');x.setDate(x.getDate()+d-1);if(dt)dt.textContent=x.toLocaleDateString('bn-BD',{weekday:'long',year:'numeric',month:'long',day:'numeric'});box.innerHTML=planTasks(d).map((v,i)=>`<label style="display:block;padding:10px 0;border-bottom:1px solid rgba(128,128,128,.18)"><input type="checkbox" class="plan-check" data-i="${i}"> ${v}</label>`).join('');const done=JSON.parse(localStorage.getItem('planDoneDays')||'[]');if(done.includes(d))document.querySelectorAll('.plan-check').forEach(x=>x.checked=true);if(p)p.textContent=`📊 Progress: ${done.length}/180 days (${Math.round(done.length/180*100)}%) • 428 topics`}
function completePlanDay(){const c=[...document.querySelectorAll('.plan-check')];if(c.some(x=>!x.checked)){alert('আজকের সব Target complete করুন');return}const d=planDay(),done=JSON.parse(localStorage.getItem('planDoneDays')||'[]');if(!done.includes(d))done.push(d);localStorage.setItem('planDoneDays',JSON.stringify(done));if(d<180)localStorage.setItem('planDay',d+1);render180DayPlan()}
function nextPlanDay(){localStorage.setItem('planDay',Math.min(180,planDay()+1));render180DayPlan()}
window.completePlanDay=completePlanDay;window.nextPlanDay=nextPlanDay;window.addEventListener('load',render180DayPlan);