const STUDY_PLAN_START='2026-09-01';
const PLAN_SUBJECTS=[{id:'bangla',name:'📖 বাংলা'},{id:'english',name:'🇬🇧 English'},{id:'math',name:'➗ Mathematics'},{id:'gk',name:'🌍 General Knowledge'}];
const QUOTES=['“শিক্ষা মানুষের মনের দরজা খুলে দেয়।”','“আজকের পরিশ্রমই আগামী দিনের আত্মবিশ্বাস।”','“অল্প অল্প করে এগিয়ে যাওয়াই একদিন বড় দূরত্ব পার করে দেয়।”','“সময়কে যে মূল্য দেয়, সফলতা একদিন তার কাছেই আসে।”','“থেমে যেও না, ধীর গতিতেও এগিয়ে চলা এগিয়ে না চলার চেয়ে ভালো।”','“স্বপ্ন শুধু দেখলেই হয় না, তাকে সত্যি করতে প্রতিদিন কাজ করতে হয়।”','“পরিশ্রম কখনো বিশ্বাসঘাতকতা করে না।”','“একদিনে সাফল্য আসে না, প্রতিদিনের ছোট ছোট চেষ্টায় আসে।”','“নিজের সঙ্গে প্রতিযোগিতা করো, গতকালের চেয়ে আজ একটু ভালো হও।”','“যে আজ শেখে, সে আগামীকাল এগিয়ে থাকে।”'];
function planDay(){const n=Number(localStorage.getItem('planDay'));return n>=1&&n<=180?n:1}
function planPhase(d){if(d<=120)return'📚 মূল পড়া';if(d<=150)return'🔄 ১ম Revision';if(d<=170)return'🔄 ২য় Revision';return'🔥 Final Revision'}
function getPlanData(){return window.topicData||{bangla:[],english:[],math:[],gk:[]}}
function buildDailyTopicPlan(){const data=getPlanData(),all=[];PLAN_SUBJECTS.forEach(s=>(data[s.id]||[]).forEach((topic,index)=>all.push({name:s.name,topic,subject:s.id,index})));const plan=Array.from({length:120},()=>[]);all.forEach((x,i)=>plan[Math.min(119,Math.floor(i*120/all.length))].push(x));return plan}
function planTasks(d){if(d<=120)return(buildDailyTopicPlan()[d-1]||[]).map(x=>`${x.name}  •  ${x.topic}`);if(d<=150)return['📖 বাংলা: ১ম Revision','🇬🇧 English: ১ম Revision','➗ Math: ১ম Revision','🌍 GK: ১ম Revision'];if(d<=170)return['📖 বাংলা: ২য় Revision','🇬🇧 English: ২য় Revision','➗ Math: ২য় Revision','🌍 GK: ২য় Revision'];return['📖 বাংলা: Final Revision','🇬🇧 English: Final Revision','➗ Math: Final Revision','🌍 GK: Final Revision']}
function render180DayPlan(){const d=planDay(),box=document.getElementById('planTasks'),t=document.getElementById('planDay'),p=document.getElementById('planProgress'),dt=document.getElementById('planDate');if(!box||!t)return;t.textContent=`Day ${d} / 180 • ${planPhase(d)}`;const x=new Date(STUDY_PLAN_START+'T00:00:00');x.setDate(x.getDate()+d-1);if(dt)dt.textContent=x.toLocaleDateString('bn-BD',{weekday:'long',year:'numeric',month:'long',day:'numeric'});const tasks=planTasks(d);box.innerHTML=tasks.map((v,i)=>`<label style="display:flex;gap:10px;align-items:flex-start;padding:14px 6px;border-bottom:1px solid rgba(128,128,128,.18);cursor:pointer"><input type="checkbox" class="plan-check" data-i="${i}" style="margin-top:4px"><span>${v}</span></label>`).join('');const done=JSON.parse(localStorage.getItem('planDoneDays')||'[]');if(done.includes(d))document.querySelectorAll('.plan-check').forEach(x=>x.checked=true);if(p)p.textContent=`📊 ${done.length}/180 দিন সম্পন্ন`}
function completePlanDay(){const c=[...document.querySelectorAll('.plan-check')];if(c.length&&c.some(x=>!x.checked)){alert('আজকের সব পড়া complete করুন');return}const d=planDay(),done=JSON.parse(localStorage.getItem('planDoneDays')||'[]');if(!done.includes(d))done.push(d);localStorage.setItem('planDoneDays',JSON.stringify(done));if(d<180)localStorage.setItem('planDay',d+1);render180DayPlan()}
function nextPlanDay(){localStorage.setItem('planDay',Math.min(180,planDay()+1));render180DayPlan()}
function renderDailyInspiration(){const host=document.getElementById('plan180');if(!host||document.getElementById('dailyInspiration'))return;const d=planDay(),q=QUOTES[(d-1)%QUOTES.length];const el=document.createElement('div');el.id='dailyInspiration';el.style.cssText='margin:14px 0;padding:18px 16px;border-radius:16px;background:linear-gradient(135deg,rgba(37,99,235,.10),rgba(139,92,246,.10));border:1px solid rgba(37,99,235,.15);text-align:center';el.innerHTML=`<div style="font-size:13px;font-weight:700;margin-bottom:7px">🌸 আজকের উক্তি</div><div style="font-size:18px;line-height:1.6;font-weight:600">${q}</div><div style="font-size:13px;opacity:.7;margin-top:8px">আজ একটু এগিয়ে যাও। আগামীকাল নিজেকেই ধন্যবাদ দেবে।</div>`;host.insertBefore(el,document.getElementById('planTasks'))}
window.completePlanDay=completePlanDay;window.nextPlanDay=nextPlanDay;window.addEventListener('load',()=>setTimeout(()=>{render180DayPlan();renderDailyInspiration()},400));