const STUDY_PLAN_START='2026-09-01';
const PLAN_LIMITS={bangla:120,english:95,math:85,gk:128};
const PLAN_SUBJECTS=[{id:'bangla',name:'📖 বাংলা'},{id:'english',name:'🇬🇧 English'},{id:'math',name:'➗ Mathematics'},{id:'gk',name:'🌍 General Knowledge'}];
function planDay(){const n=Number(localStorage.getItem('planDay'));return n>=1&&n<=180?n:1}
function planPhase(d){if(d<=120)return'📚 মূল পড়া';if(d<=150)return'🔄 ১ম Revision';if(d<=170)return'🔄 ২য় Revision';return'🔥 Final Revision'}
function getPlanData(){return{bangla:Array.isArray(window.banglaTopics)?window.banglaTopics:[],english:Array.isArray(window.englishTopics)?window.englishTopics:[],math:Array.isArray(window.mathTopics)?window.mathTopics:[],gk:Array.isArray(window.gkTopics)?window.gkTopics:[]}}
function buildDailyTopicPlan(){const data=getPlanData();const q={};PLAN_SUBJECTS.forEach(s=>q[s.id]=data[s.id].slice(0,PLAN_LIMITS[s.id]));const plan=Array.from({length:120},()=>[]);const used={bangla:0,english:0,math:0,gk:0};for(let d=0;d<120;d++){for(let k=0;k<4;k++){let best=null,bestRatio=Infinity;PLAN_SUBJECTS.forEach(s=>{if(used[s.id]>=q[s.id].length)return;const ratio=used[s.id]/q[s.id].length;if(ratio<bestRatio){best=s;bestRatio=ratio}});if(!best)break;const i=used[best.id]++;plan[d].push({name:best.name,topic:q[best.id][i],subject:best.id,index:i})}}return plan}
let DAILY_TOPIC_PLAN=[];
function getDailyTopicPlan(){if(!DAILY_TOPIC_PLAN.length)DAILY_TOPIC_PLAN=buildDailyTopicPlan();return DAILY_TOPIC_PLAN}
function planTasks(d){if(d<=120)return(getDailyTopicPlan()[d-1]||[]).map(x=>`${x.name}  •  ${x.topic}`);if(d<=150)return['📖 বাংলা: ১ম Revision','🇬🇧 English: ১ম Revision','➗ Math: ১ম Revision','🌍 GK: ১ম Revision'];if(d<=170)return['📖 বাংলা: ২য় Revision','🇬🇧 English: ২য় Revision','➗ Math: ২য় Revision','🌍 GK: ২য় Revision'];return['📖 বাংলা: Final Revision','🇬🇧 English: Final Revision','➗ Math: Final Revision','🌍 GK: Final Revision']}
function render180DayPlan(){const d=planDay(),t=document.getElementById('planDay'),box=document.getElementById('planTasks'),p=document.getElementById('planProgress'),dt=document.getElementById('planDate');if(!t||!box)return;const data=getPlanData();const ready=PLAN_SUBJECTS.some(s=>data[s.id].length);if(!ready){box.innerHTML='<div style="padding:18px;text-align:center">Topics loading...</div>';return}t.textContent=`Day ${d} / 180 • ${planPhase(d)}`;const x=new Date(STUDY_PLAN_START+'T00:00:00');x.setDate(x.getDate()+d-1);if(dt)dt.textContent=x.toLocaleDateString('bn-BD',{weekday:'long',year:'numeric',month:'long',day:'numeric'});const tasks=planTasks(d);box.innerHTML=tasks.map((v,i)=>`<label style="display:flex;gap:10px;align-items:flex-start;padding:14px 6px;border-bottom:1px solid rgba(128,128,128,.18);cursor:pointer"><input type="checkbox" class="plan-check" data-i="${i}" style="margin-top:4px"><span>${v}</span></label>`).join('');const done=JSON.parse(localStorage.getItem('planDoneDays')||'[]');if(done.includes(d))document.querySelectorAll('.plan-check').forEach(x=>x.checked=true);if(p)p.textContent=`📊 ${done.length}/180 দিন সম্পন্ন • 428 Topics`}
function completePlanDay(){const c=[...document.querySelectorAll('.plan-check')];if(c.length&&c.some(x=>!x.checked)){alert('আজকের সব পড়া complete করুন');return}const d=planDay(),done=JSON.parse(localStorage.getItem('planDoneDays')||'[]');if(!done.includes(d))done.push(d);localStorage.setItem('planDoneDays',JSON.stringify(done));if(d<180)localStorage.setItem('planDay',d+1);DAILY_TOPIC_PLAN=[];render180DayPlan()}
function nextPlanDay(){localStorage.setItem('planDay',Math.min(180,planDay()+1));DAILY_TOPIC_PLAN=[];render180DayPlan()}
window.completePlanDay=completePlanDay;window.nextPlanDay=nextPlanDay;
window.addEventListener('load',()=>{let n=0;const wait=()=>{render180DayPlan();if(!PLAN_SUBJECTS.some(s=>getPlanData()[s.id].length)&&n++<50)setTimeout(wait,200)};wait()});